apiVersion: apps/v1
kind: Deployment
metadata:
  name: o2gether-backend-depoly
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-server
        image: docker.io/locally/o2gether-backend
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: api-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 8080